export type FirebaseMvpActionDecision = "behalten" | "ausblenden" | "deaktivieren";

export type FirebaseMvpActionAuditItem = {
  id: string;
  action: string;
  screen: string;
  currentlyVisibleBeforeCleanup: boolean;
  synchronized: boolean;
  tested: boolean;
  decision: FirebaseMvpActionDecision;
  reason: string;
};

export const FIREBASE_MVP_ACTION_AUDIT: FirebaseMvpActionAuditItem[] = [
  {
    id: "online-hub-join-league",
    action: "Liga suchen / Liga beitreten",
    screen: "Online Hub",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Firestore-Repository nutzt transactionale Join-Guards; Entry-Flow-Tests decken Join-Fehlerfälle ab.",
  },
  {
    id: "online-hub-continue-last-league",
    action: "Letzte Liga laden / Weiterspielen",
    screen: "Online Hub",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Last-League-ID ist lokaler Zeiger, die Liga selbst wird aus Firestore geladen.",
  },
  {
    id: "online-hub-save-display-name",
    action: "Name speichern",
    screen: "Online User Status",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Der Anzeigename ist Identity-Metadatum und nicht Teil des Liga-Writes.",
  },
  {
    id: "online-auth-email-password",
    action: "Login / Registrierung / Logout",
    screen: "Hauptseite / Online Gate",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Firebase Auth UID ist die führende Online-Identität; Online-Routen sind ohne Login gesperrt.",
  },
  {
    id: "online-dashboard-ready-toggle",
    action: "Ready setzen / zurücknehmen",
    screen: "Online Liga Dashboard",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Bereit-Status wird pro Liga/Woche in Firestore persistiert und für die Admin-Simulation ausgewertet.",
  },
  {
    id: "online-dashboard-fantasy-draft-pick",
    action: "Fantasy-Draft Pick bestätigen",
    screen: "Online Liga Draft Room",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Picks laufen über den Fantasy-Draft-Service mit Verfügbarkeit, Turn-Validierung und atomaren Guards.",
  },
  {
    id: "online-dashboard-claim-vacant-team",
    action: "Vakantes Team übernehmen",
    screen: "Online Liga Dashboard",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Der Flow schreibt im Firebase-Modus keine belastbare Membership-/Team-Übernahme.",
  },
  {
    id: "online-dashboard-training-plan",
    action: "Trainingsplan speichern",
    screen: "Online Liga Dashboard",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Training ist im Firebase-MVP nicht als persistenter User-Write abgesichert.",
  },
  {
    id: "online-dashboard-franchise-actions",
    action: "Franchise-Strategie / Preise / Media-Ziel speichern",
    screen: "Online Liga Dashboard Expertenmodus",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Franchise-/Owner-/Pricing-Writes sind Legacy-Browser-State und nicht Firestore-synchronisiert.",
  },
  {
    id: "online-dashboard-contract-actions",
    action: "Vertrag verlängern / Spieler entlassen / Free Agent verpflichten",
    screen: "Online Liga Dashboard Expertenmodus",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Roster-Veränderungen sind im Firebase-MVP nicht transaktional über Multiplayer-State abgesichert.",
  },
  {
    id: "online-dashboard-trade-actions",
    action: "Trade vorschlagen / annehmen / ablehnen",
    screen: "Online Liga Dashboard Expertenmodus",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Trade-State besitzt keine belastbare Firestore-Sync- und Konfliktlösung.",
  },
  {
    id: "online-dashboard-legacy-draft-actions",
    action: "Prospect scouten / draften",
    screen: "Online Liga Dashboard Expertenmodus",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Legacy-Draft ist nicht der neue Fantasy-Draft und nicht im Firebase-MVP verankert.",
  },
  {
    id: "online-dashboard-coach-actions",
    action: "Coach einstellen / entlassen",
    screen: "Online Liga Dashboard Expertenmodus",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Coaching-Writes sind nicht als Firestore-Multiplayer-Aktionen umgesetzt.",
  },
  {
    id: "admin-create-league",
    action: "Liga erstellen",
    screen: "Admin Hub",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Server-Admin-Action erstellt Firestore-Liga und initialisiert den MVP-Liga-State.",
  },
  {
    id: "admin-delete-reset-league",
    action: "Liga löschen / zurücksetzen",
    screen: "Admin Hub",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: false,
    decision: "ausblenden",
    reason: "Destruktive Admin-Flows sind nicht Teil des Firebase-MVP und nicht ausreichend E2E-abgesichert.",
  },
  {
    id: "admin-debug-tools",
    action: "Debug Tools",
    screen: "Admin Hub",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Debug-Tools verändern lokalen Legacy-State und dürfen im Firebase-Modus nicht sichtbar sein.",
  },
  {
    id: "admin-draft-control",
    action: "Fantasy Draft initialisieren/starten/Auto-Draft/Abschluss prüfen",
    screen: "Admin Liga Detail",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Draft-Admin-Aktionen laufen über Server-Actions und den Fantasy-Draft-Service.",
  },
  {
    id: "admin-draft-reset",
    action: "Fantasy Draft Reset Dev/Test",
    screen: "Admin Liga Detail",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: false,
    decision: "ausblenden",
    reason: "Reset ist ein Dev/Test-Werkzeug und kein produktiver Firebase-MVP-Flow.",
  },
  {
    id: "admin-ready-week-simulation",
    action: "Alle Ready setzen / Liga starten / Woche simulieren",
    screen: "Admin Liga Detail",
    currentlyVisibleBeforeCleanup: true,
    synchronized: true,
    tested: true,
    decision: "behalten",
    reason: "Diese Aktionen laufen serverseitig, schreiben Week-State und MatchResults und blockieren doppelte Simulation.",
  },
  {
    id: "admin-revenue-sharing",
    action: "Revenue Sharing anwenden",
    screen: "Admin Liga Detail",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Die Action ist im Firebase-Admin-Backend nicht implementiert.",
  },
  {
    id: "admin-training-reset",
    action: "Trainingsplan zurücksetzen",
    screen: "Admin Liga Detail",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "Training-Admin-Writes sind nicht im Firebase-Admin-Backend implementiert.",
  },
  {
    id: "admin-gm-control-actions",
    action: "GM verwarnen / entfernen / Team vakant setzen / Legacy entfernen",
    screen: "Admin Liga Detail",
    currentlyVisibleBeforeCleanup: true,
    synchronized: false,
    tested: false,
    decision: "ausblenden",
    reason: "GM-Kontrollaktionen sind teilweise Legacy oder nicht ausreichend als Firebase-MVP-Flow getestet.",
  },
];

export function getFirebaseMvpVisibleActions() {
  return FIREBASE_MVP_ACTION_AUDIT.filter((item) => item.decision === "behalten");
}

export function getFirebaseMvpHiddenActions() {
  return FIREBASE_MVP_ACTION_AUDIT.filter((item) => item.decision === "ausblenden");
}
